package com.careernova.auth.dto;

import com.careernova.auth.enums.AuthProviderType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LoginResponseDto {

    private String accessToken;      // JWT generated by backend
    private String tokenType;        // Bearer
    private long expiresIn;          // seconds
    private Long userId;             // internal DB id
    private String email;
    private AuthProviderType providerType;
    private boolean newUser;         // true if user created now
}